# Generated by Django 4.0 on 2022-01-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('main_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='mail_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.maillist'),
        ),
    ]
