version: "3.9"

services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  homepage:
    image: yuriyarhipov/homepage
    env_file: .env
    depends_on:
      - caddy
    command: gunicorn homepage.wsgi -b 0.0.0.0:8000
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.lifecycle.post-update: "make migrations"

  watchtower:
    image: containrrr/watchtower
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: unless-stopped
