name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      TAG_NAME: echo $(date +%s)
      DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag homepage:${{TAG_NAME}}
      env:
        TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
    - name: Dockerhub auth
      run: docker login -u yuriyarhipov -p ${{env.DOCKER_HUB_TOKEN}}
    - name: Publish the image
      run: docker push yuriyarhipov/homepage:${{env.TAG_NAME}}
